#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'styling, testing and building your project before  commiting'

# Check Prettier
npm run check-format ||
{
  echo 'prettier check failed. Run npm run format, add changes and try commit again';
  false;
}

# Check ESLint
npm run check-lint ||
{
  echo "ESLint check failed. make the required changes list above, add changes and try commit again";
  false;
}

# Check tsConfig
npm run check-types ||
{
  echo 'failed  type check. make the changes require above, add changes and try commit again';
  false;
}

npm run build ||
{
  echo 'Your build failed, view the errors above';
  false;
}

echo "success commite"